name: Security Scan

on: 
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs: 
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@1754bbe224200aa1d820cdf795d42de54b34245f # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'