name: Security Scan

on: 
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs: 
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@bd958ead76ac7c72acf4976c244c47eef89c84f7 # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'