name: 'Mark or close stale issues and PRs'

on: 
  schedule:
    - cron: '0 0 * * 5'   # Runs every Friday midnight
  workflow_dispatch:

jobs:
  call-shared-stale:
    uses: clouddrove/github-shared-workflows/.github/workflows/stale_pr.yml@e075b2c8f7a739fc1f2a0d13133abd16c943dec2 # pinned to latest
    with: 
      days-before-issue-stale: 30
      days-before-pr-stale: 30
      days-before-issue-close: 10
      days-before-pr-close: 10
