name: Tag Release

on:
  pull_request:
    types: [closed]

jobs: 
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@e075b2c8f7a739fc1f2a0d13133abd16c943dec2 # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}